name: TailwindTraders Website Pipelines
on:
  push:
    branches: [main, create-cicd-action, ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr-build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker build
      working-directory: Source
      run: |
        docker-compose build --no-cache 

  main-build:
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Docker build
      working-directory: Source
      run: |
        docker-compose build --no-cache 

  nightly-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set Azure subscription
      run: |
        az account set -s ${{ secrets.AZURE_SUBSCRIPTION }}
    
    - name: Docker login
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Docker build and push
      working-directory: Deploy/powershell
      shell: powershell
      run: |
        Build-Push.ps1 -resourceGroup ${{ secrets.RESOURCE_GROUP }} -acrName ${{ secrets.ACR_NAME }}